#==========================================================
# セーブデータに関する設定（1人プレイ専用）
#==========================================================
game:
  # ニコ生プレイ時のモード（ ranking / multi ）
  launch_mode: 'ranking'

#==========================================================
# セーブデータに関する設定（1人プレイ専用）
#==========================================================
storage:
  # セーブデータ用 localStorage の key につけるプレフィックス
  # ローカルデバッグで他のゲームのセーブデータと
  # 混ざらないようにするために使用します
  prefix: 'game'
